name: clean_architecture
description: An example project based on Reso Coder's Flutter TDD Clean Architecture

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  
  # Service locator
  get_it: ^2.0.1

  # State management
  bloc: ^8.0.3

  # Value-equality
  equatable: ^0.4.0

  # Functional programming
  dartz: ^0.8.6

  # Remote API
  connectivity: ^0.4.3+7
  http: ^0.12.0+2

  # Local cache
  shared_preferences: ^0.5.3+4

dev_dependencies:

  flutter_test:
    sdk: flutter

  # Code standards
  flutter_lints: ^1.0.0

  # API Fakes, Mocks, behavior verification, and stubbing
  mockito: ^5.1.0

flutter:

  # Android-style fonts & icons
  uses-material-design: true
