name: clean_architecture
description: An example project based on Reso Coder's Flutter TDD Clean Architecture

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  
  # Service locator
  get_it: ^7.2.0

  # State management
  bloc: ^8.0.3

  # Value-equality
  equatable: ^2.0.3

  # Functional programming for error handling using error objects
  dartz: ^0.10.1

  # Remote API
  connectivity: ^3.0.6
  http: ^0.13.4

  # Local cache
  shared_preferences: ^2.0.13

dev_dependencies:

  flutter_test:
    sdk: flutter

  # Code standards
  flutter_lints: ^1.0.4

  # API Fakes, Mocks, behavior verification, and stubbing
  mockito: ^5.1.0

flutter:

  # Android-style fonts & icons
  uses-material-design: true
